[battery]
enabled = true
interval = 10

[brightness]
enabled = true
interval = 5
device = "nvidia_wmi_ec_backlight"

[date]
enabled = true
interval = 5
format = "%d/%m/%Y %H:%M"

[pulse]
enabled = true
interval = 300

[temp]
enabled = true
interval = 5
device = "k10temp"
