bar_type = "dwlb"

[battery]
enabled = true
interval = 10

[brightness]
enabled = true
interval = 5
device = "nvidia_wmi_ec_backlight"

[date]
enabled = true
interval = 5
format = "%d/%m/%Y %H:%M"

[portage]
enabled = true
interval = 3600
watch_file = "/var/cache/eix/portage.eix"

[pulse]
enabled = true
interval = 300

[temp]
enabled = true
interval = 5
device = "k10temp"
